### ISSUE TITLE
Large PRs

### ISSUE THREAD

**Issue by agzam** [wandersoncferreira/code-review#43]
Large PRs may make it look like Emacs is stuck and not loading. Often it just takes too long. Maybe a progress-reporter?

**Comment by wandersoncferreira** [comment]
What do you mean by "Large PRs"? PRs with huge diffs? This is in fact a problem right now, I need to change the strategy to render the comments in order to speed up the rendering however I believe a more severe case of this issue will still remain. Github does not handle large diffs properly too:
![Screen Shot 2021-11-12 at 10 27 00 PM](https://user-images.githubusercontent.com/17708295/141600686-81b148e3-1c33-4b32-b1fe-2f65b644107c.png)

![Screen Shot 2021-11-12 at 10 27 10 PM](https://user-images.githubusercontent.com/17708295/141600690-e636f198-f386-4b79-b84c-c94c9a6bef90.png)

From this PR https://github.com/python/cpython/pull/29513/files

**Comment by agzam** [comment]
Even before rendering, I think it takes too long for PRs with big diffs to load.

**Comment by wandersoncferreira** [comment]
I commented this line https://github.com/wandersoncferreira/code-review/blob/759f8a7eee7e2c49f6c3dadcad2e8ccb6f3bae27/code-review.el#L168 that triggers the rendering functions and the Python PR above was added in the buffer in less than 5seconds. The issue here is that `magit-wash-sequence` traverse the buffer line by line (in this case 66.6k lines) and verifies which `properties` each line should have.

I used this inner working of the library to stick `comments` in it. So now, not only we render the appropriate faces for each line but also I make 1 extra call to verify if that line should have a comment or not. This call had some info that called `closql` which made it *very very* slow and I already changed to use mutable in memory var, however I believe more improvements are still possible.

But this will not change the fact that `Magit-diff` goes line by line in the buffer :/

**Comment by wandersoncferreira** [comment]
I just tested `Magit-diff` stock without that additional call I mentioned above and the buffer was rendered in a few seconds without a problem. I will put some priority into this performance bottleneck :/

**Comment by wandersoncferreira** [comment]
WOW!
![Screen Shot 2021-11-12 at 11 33 07 PM](https://user-images.githubusercontent.com/17708295/141602633-e08aa188-236b-4734-9bea-e6f93eeb98b6.png)

Investigating alternatives.. https://emacs.stackexchange.com/questions/3821/a-faster-method-to-obtain-line-number-at-pos-in-large-buffers

**Comment by wandersoncferreira** [comment]
@agzam could you test the latest version of the package on the slow PR you had?
![Screen Shot 2021-11-13 at 10 47 33 AM](https://user-images.githubusercontent.com/17708295/141646240-bddb9187-f79a-4b64-8d14-d330e07a8c65.png)

This picture looks like what I was expecting for performance bottleneck.. calls to `closql` in hot path which can be improved a lot.

**Comment by agzam** [comment]
I think you've misunderstood. I wasn't talking about the performance, even though, of course, I love the improvements :).
I'm just saying: whenever it has to fetch a large PR, the UI does nothing, and there's no indication of anything happening. I have never done anything similar, but I think simply wrapping things in a progress-reporter block would show the progress in the mode-line: https://www.gnu.org/software/emacs/manual/html_node/elisp/Progress.html

I know, Forge doesn't do that either, but I know better than telling @tarsius what to do. Besides, it's just an idea, I'm not telling you "what to do" either :)

**Comment by wandersoncferreira** [comment]
@agzam I understood your point but I did a poor explaining on my intent afterwards rs. I wanted to speed up the load process so we do not need Progress Reports for larger diffs (to some definition of large) but the idea of a progress report is interestin. I did a hacky prototype of this feature in #47 . Do you mind testing with your large PRs and see how it looks like?

There are two progress reports, i) fetch diff and ii) load (render) PR. The second one is more complicated because for the Python PR I linked here with a diff containing 66k loc we would need to `sit-for` some small number of time once in a while to display better reporting but ofc this does not make sense to me.. making the process slower to gain some sugar. anyway, at least the current POC version provides _some_ way to inform the user that the system is working.

**Comment by wandersoncferreira** [comment]
A naive progress report was added in the new release. I am closing this issue for now.
